### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by fjnok** [fjnok/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by fjnok** [comment]
これから対応します

**Comment by sunayamanaoki** [comment]
2fd7465 で対応されました

**Comment by fjnok** [comment]
2fd7465 で対応されました
